### ISSUE TITLE
when field has std value its not being overridden by user's empty input

### ISSUE THREAD

**Issue by towfiqi** [bainternet/Admin-Page-Class#46]
When a textfield, textarea field has std value, user cannot remove the default value to keep the field empty. the std value should be overridden by the updated settings.

**Comment by towfiqi** [comment]
to recreate the issue, add an std value to your text and textarea field. Then call them in your template files. now go to back-end again and remove the default values for your and click the save button. now notice the default values are still there.

**Comment by brasofilo** [comment]
Hi @towfiqi , can you make a mini-plugin that demonstrates the issue?

**Comment by towfiqi** [comment]
I am using this with a theme that is still under construction :/ 
the issue exist in the core files. In class-usage-demo.php file you cannot remove the default std values of text field and the textarea from the options page. they are always there.

**Comment by towfiqi** [comment]
@brasofilo do you want me to me to setup a wordpress and install apc in it to demonstrate the issue? let me know.

**Comment by bainternet** [comment]
Sorry for the late replay,
but actually its working the way it was planned to work, let me explain:

if the value is empty string the its not stored in the database.
the only problem is that if you clear a field and reload the panel to set another option and save the field you cleared is set back to its default value.
Fixed in 1.3.0

thanks.
